title: SlugBase Documentation
description: Self-hosted bookmark manager with optional link forwarding
theme: minima
baseurl: ""
url: "https://slugbase.github.io"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - Gemfile
  - Gemfile.lock
